[project]
name = "mcp-tool-only-server"
version = "0.1.0"
description = "MCP server that only recognizes tools"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [ "mcp>=1.10.1",]
[[project.authors]]
name = "Trevor Jackson"
email = "jacksontrevor297@gmail.com"

[build-system]
requires = [ "hatchling",]
build-backend = "hatchling.build"

[project.scripts]
mcp-tool-only-server = "mcp_tool_only_server:main"
